package Vista;

import Modelo.Empleado;
import Modelo.Gimnasio;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author dam
 */
public class PnlEjercicio extends javax.swing.JPanel {

    Gimnasio miGym;

    /**
     * Creates new form PnlEjercicio
     */
    public PnlEjercicio(Gimnasio gym) {
        miGym = gym;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpNivel = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodRut = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        RbPrincipiante = new javax.swing.JRadioButton();
        RbPro = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaDescripcion = new javax.swing.JTextArea();
        BtnAceptar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("EJERCICIOS");

        jLabel2.setText("Código Rutina:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Nivel:");

        jLabel5.setText("Descripción");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        grpNivel.add(RbPrincipiante);
        RbPrincipiante.setText("Principiante");

        grpNivel.add(RbPro);
        RbPro.setText("Pro");

        TaDescripcion.setColumns(20);
        TaDescripcion.setRows(5);
        jScrollPane1.setViewportView(TaDescripcion);

        BtnAceptar.setText("Aceptar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RbPrincipiante)
                                .addGap(18, 18, 18)
                                .addComponent(RbPro))
                            .addComponent(txtCodRut)
                            .addComponent(txtNombre))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(BtnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCancelar)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RbPrincipiante)
                    .addComponent(RbPro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAceptar)
                    .addComponent(BtnCancelar))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        int tipo = RbPrincipiante.isSelected() ? 1 : 0;
        String nombre = txtNombre.getText();
        String Desc = TaDescripcion.getText();
        int codRutina;
        
        try {
            codRutina = Integer.parseInt(txtCodRut.getText());
        }
        catch (NumberFormatException ex) {
            codRutina = 0;
        }
        
        
        comprobarCampos(codRutina, nombre);
        comprobarDisponibilidad(codRutina, nombre, tipo, Desc);
        borrarCampos();
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        borrarCampos();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    public void comprobarCampos(int codRutina, String nombre) {
        if (nombre.equals("")) {
            JOptionPane.showMessageDialog(this, "Campos incompletos", "error", JOptionPane.ERROR_MESSAGE);
            txtCodRut.requestFocus();
        }
    }
    
    public void comprobarDisponibilidad(int codRutina, String nombre, int tipo, String Desc) {
        /*int i = miGym.ComprobarRutina(codRutina); 
        if (i != -1) {
            JOptionPane.showMessageDialog(this, "Ejercicio duplicado", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (i == -1) {
            miGym.anadirRutina(codRutina, nombre, tipo, Desc);
            JOptionPane.showMessageDialog(this, "Ejercicio Añadido", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } */
        
        Integer i = miGym.ComprobarRutina(codRutina);
        if (i != -1) { // si devuelve un valor distinto de -1 es que ha encontrado el valor
            JOptionPane.showMessageDialog(this, "Código de rutina existente", "error", JOptionPane.ERROR_MESSAGE);
        } else {
            miGym.anadirRutina(codRutina, nombre, tipo, Desc);
            JOptionPane.showMessageDialog(this, "Añadido");
        }
    }
    public void borrarCampos() {
        txtCodRut.setText("");
        txtNombre.setText("");
        TaDescripcion.setText("");
        RbPrincipiante.setSelected(false);
        RbPro.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JRadioButton RbPrincipiante;
    private javax.swing.JRadioButton RbPro;
    private javax.swing.JTextArea TaDescripcion;
    private javax.swing.ButtonGroup grpNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodRut;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
