
package Vista;

import Modelo.Empleado;
import Modelo.Gimnasio;

/**
 *
 * @author dam
 */
public class VtnMenu extends javax.swing.JFrame {
    VtnAcceso vtnAcceso;
    PnlClientes pnlClientes;
    Gimnasio miGym;
    PnlEjercicio Ejercicio;
    PnlAsignar pnlAsignar;
    /**
     * Creates new form VtnMenu
     * @param login
     * @param gym
     */
    public VtnMenu(String login, Gimnasio gym) {
        miGym = gym;
        pnlAsignar = new PnlAsignar(miGym);
        pnlClientes = new PnlClientes(miGym);
        vtnAcceso = new VtnAcceso(miGym);
        Ejercicio = new PnlEjercicio(miGym);
        initComponents();
    }
    public void comprobarTipo() {
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuOpciones = new javax.swing.JMenu();
        MnuEjercicio = new javax.swing.JMenuItem();
        MnuAlta = new javax.swing.JMenuItem();
        MnuAsignacion = new javax.swing.JMenuItem();
        MnuCheckin = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        MnuCerrarS = new javax.swing.JMenuItem();
        MnuCerrarA = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        mnuOpciones.setText("Opciones");

        MnuEjercicio.setText("Alta Ejercicio");
        MnuEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuEjercicioActionPerformed(evt);
            }
        });
        mnuOpciones.add(MnuEjercicio);

        MnuAlta.setText("Alta clientes");
        MnuAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAltaActionPerformed(evt);
            }
        });
        mnuOpciones.add(MnuAlta);

        MnuAsignacion.setText("Asignar Actividad");
        MnuAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAsignacionActionPerformed(evt);
            }
        });
        mnuOpciones.add(MnuAsignacion);

        MnuCheckin.setText("Check-In");
        mnuOpciones.add(MnuCheckin);

        jMenuBar1.add(mnuOpciones);

        mnuSalir.setText("Salir");

        MnuCerrarS.setText("Cerrar Sesión");
        MnuCerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCerrarSActionPerformed(evt);
            }
        });
        mnuSalir.add(MnuCerrarS);

        MnuCerrarA.setText("Cerrar aplicación");
        MnuCerrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCerrarAActionPerformed(evt);
            }
        });
        mnuSalir.add(MnuCerrarA);

        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAltaActionPerformed
        quitarPaneles();
        pnlClientes = new PnlClientes(miGym);
        pnlClientes.setVisible(true);
        getContentPane().add(pnlClientes);
        pack();
    }//GEN-LAST:event_MnuAltaActionPerformed

    private void MnuCerrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCerrarAActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MnuCerrarAActionPerformed

    private void MnuCerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCerrarSActionPerformed
        quitarPaneles();
        dispose();
        vtnAcceso = new VtnAcceso(miGym);
        vtnAcceso.setVisible(true);
        pack();
    }//GEN-LAST:event_MnuCerrarSActionPerformed

    private void MnuEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuEjercicioActionPerformed
        quitarPaneles();
        Ejercicio.setVisible(true);
        getContentPane().add(Ejercicio);
        pack();
    }//GEN-LAST:event_MnuEjercicioActionPerformed

    private void MnuAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAsignacionActionPerformed
        quitarPaneles();
        pnlAsignar = new PnlAsignar(miGym);
        pnlAsignar.setVisible(true);
        getContentPane().add(pnlAsignar);
        pack();
    }//GEN-LAST:event_MnuAsignacionActionPerformed

    public void quitarPaneles() {
        Ejercicio.setVisible(false);
        vtnAcceso.setVisible(false);
        pnlClientes.setVisible(false);
        pnlAsignar.setVisible(false);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuAlta;
    private javax.swing.JMenuItem MnuAsignacion;
    private javax.swing.JMenuItem MnuCerrarA;
    private javax.swing.JMenuItem MnuCerrarS;
    private javax.swing.JMenuItem MnuCheckin;
    private javax.swing.JMenuItem MnuEjercicio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
